import com.stackleader.brms.training.model.CreditCardApplication;

global org.slf4j.Logger LOG;

declare IsValidSelectedProduct
end

rule "Student allowed products"
agenda-group "product"
when
    IsStudent()
    CreditCardApplication(productCode memberOf ["TRAVEL"])
then
    insert(new IsValidSelectedProduct());
end

rule "Standard allowed products"
agenda-group "product"
when
    not IsStudent()
    CreditCardApplication(productCode memberOf ["TRAVEL", "REWARDS"])
then
    insert(new IsValidSelectedProduct());
end

rule "product complete"
agenda-group "product"
when
    IsValidSelectedProduct()
then
    kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup("approved").setFocus();
end